###
# listar
GET http://localhost:8080/prueba/nacionalidad
Accept: application/json

###
# obtener
GET http://localhost:8080/prueba/nacionalidad/4/
Accept: application/json

###
# guardar
POST http://localhost:8080/prueba/nacionalidad
Content-Type: application/json

{
  "descripcion": "Brasil"
}

###
# actualizar
PUT http://localhost:8080/prueba/nacionalidad
Content-Type: application/json

{
  "id": 4,
  "descripcion": "Brazil"
}

###
# eliminar
DELETE http://localhost:8080/prueba/nacionalidad/4/
Accept: application/json


